### ISSUE TITLE
chrome back error

### ISSUE THREAD

**Issue by dahuahe** [kensodemann/test-nav-strategies#1]
Error: Uncaught (in promise): TypeError: ti.done is not a function
TypeError: ti.done is not a function
    at NavControllerBase._fireError (http://localhost:8100/build/vendor.js:42819:16)
    at NavControllerBase._failed (http://localhost:8100/build/vendor.js:42810:14)
    at http://localhost:8100/build/vendor.js:42865:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4508:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)
    at http://localhost:8100/build/polyfills.js:3:14076
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
    at c (http://localhost:8100/build/polyfills.js:3:13535)
    at http://localhost:8100/build/polyfills.js:3:14107
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9888)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:5143)
    at o (http://localhost:8100/build/polyfills.js:3:2203)
    at <anonymous>

**Comment by kensodemann** [comment]
Closing. This is not an issue with the demo application. It is an issue with the Ionic Framework.

See here: https://github.com/ionic-team/ionic/issues/12499
